
server:
  port: 8091

eureka:
  #eueka 主机名
  instance:
    hostname: 127.0.0.1
  client:
    #提供者和消费者的注册地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: edu-school-provider
spring.datasource:
  name: edu-school-provider
  url: jdbc:mysql://127.0.0.1:3306/edu?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
  tomcat:
    max-active: 1200
    max-wait: 1000
    initial-wait : 500
#mybaits配置，用于xml与dao层对应
mybatis:
  mapper-locations: classpath:mapper/*.xml