
server:
  port: 8081

spring:
  application:
    name: edu-school-consumer
eureka:
  #eueka 主机名
  instance:
    hostname: 127.0.0.1
  client:
    #提供者和消费者的注册地址
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

feign:
  hystrix:
    enabled: true